# Generated by Django 3.1.4 on 2020-12-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('idDrink', models.AutoField(primary_key=True, serialize=False)),
                ('strDrink', models.CharField(max_length=37)),
                ('strDrinkAlternate', models.CharField(blank=True, max_length=30, null=True)),
                ('strDrinkES', models.CharField(blank=True, max_length=30, null=True)),
                ('strDrinkDE', models.CharField(blank=True, max_length=28, null=True)),
                ('strDrinkFR', models.CharField(blank=True, max_length=31, null=True)),
                ('strDrinkZHHANS', models.CharField(blank=True, max_length=7, null=True)),
                ('strDrinkZHHANT', models.CharField(blank=True, max_length=7, null=True)),
                ('strTags', models.CharField(blank=True, max_length=42, null=True)),
                ('strVideo', models.CharField(blank=True, max_length=30, null=True)),
                ('strCategory', models.CharField(max_length=20)),
                ('strIBA', models.CharField(blank=True, max_length=21, null=True)),
                ('strAlcoholic', models.CharField(blank=True, max_length=16, null=True)),
                ('strGlass', models.CharField(max_length=24)),
                ('strInstructions', models.CharField(blank=True, max_length=2524, null=True)),
                ('strInstructionsES', models.CharField(blank=True, max_length=30, null=True)),
                ('strInstructionsDE', models.CharField(blank=True, max_length=879, null=True)),
                ('strInstructionsFR', models.CharField(blank=True, max_length=30, null=True)),
                ('strInstructionsZHHANS', models.CharField(blank=True, max_length=30, null=True)),
                ('strInstructionsZHHANT', models.CharField(blank=True, max_length=30, null=True)),
                ('strDrinkThumb', models.CharField(max_length=69)),
                ('strIngredient1', models.CharField(max_length=26)),
                ('strIngredient2', models.CharField(max_length=26)),
                ('strIngredient3', models.CharField(blank=True, max_length=26, null=True)),
                ('strIngredient4', models.CharField(blank=True, max_length=21, null=True)),
                ('strIngredient5', models.CharField(blank=True, max_length=24, null=True)),
                ('strIngredient6', models.CharField(blank=True, max_length=26, null=True)),
                ('strIngredient7', models.CharField(blank=True, max_length=20, null=True)),
                ('strIngredient8', models.CharField(blank=True, max_length=17, null=True)),
                ('strIngredient9', models.CharField(blank=True, max_length=13, null=True)),
                ('strIngredient10', models.CharField(blank=True, max_length=13, null=True)),
                ('strIngredient11', models.CharField(blank=True, max_length=13, null=True)),
                ('strIngredient12', models.CharField(blank=True, max_length=13, null=True)),
                ('strIngredient13', models.CharField(blank=True, max_length=30, null=True)),
                ('strIngredient14', models.CharField(blank=True, max_length=30, null=True)),
                ('strIngredient15', models.CharField(blank=True, max_length=30, null=True)),
                ('strMeasure1', models.CharField(blank=True, max_length=19, null=True)),
                ('strMeasure2', models.CharField(blank=True, max_length=39, null=True)),
                ('strMeasure3', models.CharField(blank=True, max_length=24, null=True)),
                ('strMeasure4', models.CharField(blank=True, max_length=21, null=True)),
                ('strMeasure5', models.CharField(blank=True, max_length=25, null=True)),
                ('strMeasure6', models.CharField(blank=True, max_length=17, null=True)),
                ('strMeasure7', models.CharField(blank=True, max_length=22, null=True)),
                ('strMeasure8', models.CharField(blank=True, max_length=15, null=True)),
                ('strMeasure9', models.CharField(blank=True, max_length=19, null=True)),
                ('strMeasure10', models.CharField(blank=True, max_length=13, null=True)),
                ('strMeasure11', models.CharField(blank=True, max_length=14, null=True)),
                ('strMeasure12', models.CharField(blank=True, max_length=13, null=True)),
                ('strMeasure13', models.CharField(blank=True, max_length=30, null=True)),
                ('strMeasure14', models.CharField(blank=True, max_length=30, null=True)),
                ('strMeasure15', models.CharField(blank=True, max_length=30, null=True)),
                ('strCreativeCommonsConfirmed', models.CharField(max_length=3)),
                ('dateModified', models.CharField(max_length=19)),
            ],
            options={
                'db_table': 'drinks',
            },
        ),
    ]
