# Generated by Django 3.1.4 on 2020-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('idDrink', models.AutoField(primary_key=True, serialize=False)),
                ('strDrink', models.CharField(max_length=37)),
                ('strDrinkAlternate', models.CharField(blank=True, max_length=30)),
                ('strDrinkES', models.CharField(blank=True, max_length=30)),
                ('strDrinkDE', models.CharField(blank=True, max_length=28)),
                ('strDrinkFR', models.CharField(blank=True, max_length=31)),
                ('strDrinkZHHANS', models.CharField(blank=True, max_length=7)),
                ('strDrinkZHHANT', models.CharField(blank=True, max_length=7)),
                ('strTags', models.CharField(blank=True, max_length=42)),
                ('strVideo', models.CharField(blank=True, max_length=30)),
                ('strCategory', models.CharField(max_length=20)),
                ('strIBA', models.CharField(blank=True, max_length=21)),
                ('strAlcoholic', models.CharField(blank=True, max_length=16)),
                ('strGlass', models.CharField(max_length=24)),
                ('strInstructions', models.CharField(blank=True, max_length=2524)),
                ('strInstructionsES', models.CharField(blank=True, max_length=30)),
                ('strInstructionsDE', models.CharField(blank=True, max_length=879)),
                ('strInstructionsFR', models.CharField(blank=True, max_length=30)),
                ('strInstructionsZHHANS', models.CharField(blank=True, max_length=30)),
                ('strInstructionsZHHANT', models.CharField(blank=True, max_length=30)),
                ('strDrinkThumb', models.CharField(max_length=69)),
                ('strIngredient1', models.CharField(max_length=26)),
                ('strIngredient2', models.CharField(max_length=26)),
                ('strIngredient3', models.CharField(blank=True, max_length=26)),
                ('strIngredient4', models.CharField(blank=True, max_length=21)),
                ('strIngredient5', models.CharField(blank=True, max_length=24)),
                ('strIngredient6', models.CharField(blank=True, max_length=26)),
                ('strIngredient7', models.CharField(blank=True, max_length=20)),
                ('strIngredient8', models.CharField(blank=True, max_length=17)),
                ('strIngredient9', models.CharField(blank=True, max_length=13)),
                ('strIngredient10', models.CharField(blank=True, max_length=13)),
                ('strIngredient11', models.CharField(blank=True, max_length=13)),
                ('strIngredient12', models.CharField(blank=True, max_length=13)),
                ('strIngredient13', models.CharField(blank=True, max_length=30)),
                ('strIngredient14', models.CharField(blank=True, max_length=30)),
                ('strIngredient15', models.CharField(blank=True, max_length=30)),
                ('strMeasure1', models.CharField(blank=True, max_length=19)),
                ('strMeasure2', models.CharField(blank=True, max_length=39)),
                ('strMeasure3', models.CharField(blank=True, max_length=24)),
                ('strMeasure4', models.CharField(blank=True, max_length=21)),
                ('strMeasure5', models.CharField(blank=True, max_length=25)),
                ('strMeasure6', models.CharField(blank=True, max_length=17)),
                ('strMeasure7', models.CharField(blank=True, max_length=22)),
                ('strMeasure8', models.CharField(blank=True, max_length=15)),
                ('strMeasure9', models.CharField(blank=True, max_length=19)),
                ('strMeasure10', models.CharField(blank=True, max_length=13)),
                ('strMeasure11', models.CharField(blank=True, max_length=14)),
                ('strMeasure12', models.CharField(blank=True, max_length=13)),
                ('strMeasure13', models.CharField(blank=True, max_length=30)),
                ('strMeasure14', models.CharField(blank=True, max_length=30)),
                ('strMeasure15', models.CharField(blank=True, max_length=30)),
                ('strCreativeCommonsConfirmed', models.CharField(max_length=3)),
                ('dateModified', models.CharField(max_length=19)),
            ],
        ),
    ]
