# Generated by Django 3.1.4 on 2020-12-27 15:40

from django.db import migrations


def link_category(apps, schema_editor):
    Drinks = apps.get_model('drinks', 'Drinks')
    Category = apps.get_model('drinks', 'Category')
    for drink in Drinks.objects.all():
        if drink.strCategory is not None:
            category, created = Category.objects.get_or_create(name=drink.strCategory)
            drink.category_link = category
            drink.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_drinks_category_link'),
    ]

    operations = [
        migrations.RunPython(link_category),
    ]
