# Generated by Django 3.1.4 on 2020-12-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_transfer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='strCategory',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='category_link',
            new_name='category',
        ),
    ]
