# Generated by Django 3.1.4 on 2020-12-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0007_auto_20201227_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='category',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='drinks.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinks',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
