from django.db import models


class Drinks(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=37)
    name_alternate = models.CharField(max_length=30, blank=True, null=True)
    name_es = models.CharField(max_length=30, blank=True, null=True)
    name_de = models.CharField(max_length=28, blank=True, null=True)
    name_fr = models.CharField(max_length=31, blank=True, null=True)
    name_zhhans = models.CharField(max_length=7, blank=True, null=True)
    name_zhhant = models.CharField(max_length=7, blank=True, null=True)
    tags = models.CharField(max_length=42, blank=True, null=True)
    video = models.CharField(max_length=30, blank=True, null=True)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    iba = models.CharField(max_length=21, blank=True, null=True)
    alcoholic = models.CharField(max_length=16, blank=True, null=True)
    glass = models.CharField(max_length=24)
    instructions = models.CharField(max_length=2524, blank=True, null=True)
    instructions_es = models.CharField(max_length=30, blank=True, null=True)
    instructions_de = models.CharField(max_length=879, blank=True, null=True)
    instructions_fr = models.CharField(max_length=30, blank=True, null=True)
    instructions_zhhans = models.CharField(max_length=30, blank=True, null=True)
    instructions_zhhant = models.CharField(max_length=30, blank=True, null=True)
    image = models.CharField(max_length=69)
    ingredient1 = models.CharField(max_length=26)
    ingredient2 = models.CharField(max_length=26)
    ingredient3 = models.CharField(max_length=26, blank=True, null=True)
    ingredient4 = models.CharField(max_length=21, blank=True, null=True)
    ingredient5 = models.CharField(max_length=24, blank=True, null=True)
    ingredient6 = models.CharField(max_length=26, blank=True, null=True)
    ingredient7 = models.CharField(max_length=20, blank=True, null=True)
    ingredient8 = models.CharField(max_length=17, blank=True, null=True)
    ingredient9 = models.CharField(max_length=13, blank=True, null=True)
    ingredient10 = models.CharField(max_length=13, blank=True, null=True)
    ingredient11 = models.CharField(max_length=13, blank=True, null=True)
    ingredient12 = models.CharField(max_length=13, blank=True, null=True)
    ingredient13 = models.CharField(max_length=30, blank=True, null=True)
    ingredient14 = models.CharField(max_length=30, blank=True, null=True)
    ingredient15 = models.CharField(max_length=30, blank=True, null=True)
    measure1 = models.CharField(max_length=19, blank=True, null=True)
    measure2 = models.CharField(max_length=39, blank=True, null=True)
    measure3 = models.CharField(max_length=24, blank=True, null=True)
    measure4 = models.CharField(max_length=21, blank=True, null=True)
    measure5 = models.CharField(max_length=25, blank=True, null=True)
    measure6 = models.CharField(max_length=17, blank=True, null=True)
    measure7 = models.CharField(max_length=22, blank=True, null=True)
    measure8 = models.CharField(max_length=15, blank=True, null=True)
    measure9 = models.CharField(max_length=19, blank=True, null=True)
    measure10 = models.CharField(max_length=13, blank=True, null=True)
    measure11 = models.CharField(max_length=14, blank=True, null=True)
    measure12 = models.CharField(max_length=13, blank=True, null=True)
    measure13 = models.CharField(max_length=30, blank=True, null=True)
    measure14 = models.CharField(max_length=30, blank=True, null=True)
    measure15 = models.CharField(max_length=30, blank=True, null=True)
    creative_commons_confirmed = models.CharField(max_length=3)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'drinks'


class Category(models.Model):
    name = models.CharField(max_length=20)
