from django.db import models


class Drinks(models.Model):
    idDrink = models.AutoField(primary_key=True)
    strDrink = models.CharField(max_length=37)
    strDrinkAlternate = models.CharField(max_length=30, blank=True)
    strDrinkES = models.CharField(max_length=30, blank=True)
    strDrinkDE = models.CharField(max_length=28, blank=True)
    strDrinkFR = models.CharField(max_length=31, blank=True)
    strDrinkZHHANS = models.CharField(max_length=7, blank=True)
    strDrinkZHHANT = models.CharField(max_length=7, blank=True)
    strTags = models.CharField(max_length=42, blank=True)
    strVideo = models.CharField(max_length=30, blank=True)
    strCategory = models.CharField(max_length=20)
    strIBA = models.CharField(max_length=21, blank=True)
    strAlcoholic = models.CharField(max_length=16, blank=True)
    strGlass = models.CharField(max_length=24)
    strInstructions = models.CharField(max_length=2524, blank=True)
    strInstructionsES = models.CharField(max_length=30, blank=True)
    strInstructionsDE = models.CharField(max_length=879, blank=True)
    strInstructionsFR = models.CharField(max_length=30, blank=True)
    strInstructionsZHHANS = models.CharField(max_length=30, blank=True)
    strInstructionsZHHANT = models.CharField(max_length=30, blank=True)
    strDrinkThumb = models.CharField(max_length=69)
    strIngredient1 = models.CharField(max_length=26)
    strIngredient2 = models.CharField(max_length=26)
    strIngredient3 = models.CharField(max_length=26, blank=True)
    strIngredient4 = models.CharField(max_length=21, blank=True)
    strIngredient5 = models.CharField(max_length=24, blank=True)
    strIngredient6 = models.CharField(max_length=26, blank=True)
    strIngredient7 = models.CharField(max_length=20, blank=True)
    strIngredient8 = models.CharField(max_length=17, blank=True)
    strIngredient9 = models.CharField(max_length=13, blank=True)
    strIngredient10 = models.CharField(max_length=13, blank=True)
    strIngredient11 = models.CharField(max_length=13, blank=True)
    strIngredient12 = models.CharField(max_length=13, blank=True)
    strIngredient13 = models.CharField(max_length=30, blank=True)
    strIngredient14 = models.CharField(max_length=30, blank=True)
    strIngredient15 = models.CharField(max_length=30, blank=True)
    strMeasure1 = models.CharField(max_length=19, blank=True)
    strMeasure2 = models.CharField(max_length=39, blank=True)
    strMeasure3 = models.CharField(max_length=24, blank=True)
    strMeasure4 = models.CharField(max_length=21, blank=True)
    strMeasure5 = models.CharField(max_length=25, blank=True)
    strMeasure6 = models.CharField(max_length=17, blank=True)
    strMeasure7 = models.CharField(max_length=22, blank=True)
    strMeasure8 = models.CharField(max_length=15, blank=True)
    strMeasure9 = models.CharField(max_length=19, blank=True)
    strMeasure10 = models.CharField(max_length=13, blank=True)
    strMeasure11 = models.CharField(max_length=14, blank=True)
    strMeasure12 = models.CharField(max_length=13, blank=True)
    strMeasure13 = models.CharField(max_length=30, blank=True)
    strMeasure14 = models.CharField(max_length=30, blank=True)
    strMeasure15 = models.CharField(max_length=30, blank=True)
    strCreativeCommonsConfirmed = models.CharField(max_length=3)
    dateModified = models.CharField(max_length=19)
 
